saga:
  name: saga
  chainId: 2744466489002000
  domainId: 33333
  protocol: ethereum
  rpcUrls:
    - http: https://truelens-2744466489002000-1.jsonrpc.sagarpc.io
  isTestnet: true
  nativeToken:
    name: TRUE
    symbol: TRUE
    decimals: 18

rootstock:
  name: rootstock
  chainId: 31
  domainId: 31
  protocol: ethereum
  rpcUrls:
    - http: https://public-node.testnet.rsk.co
  isTestnet: true
  nativeToken:
    name: tRBTC
    symbol: tRBTC
    decimals: 18 